# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4c0c16ddc8fd58b91284d6aed18d2bddd733e91ad8a1c3dbc026edb350f7bb1587ff8a63d95113ed8c6113a58408231893b82dae28c703b0937131b5300a431

test:
  secret_key_base: 75979b6f6f383dcba67774b690441a1954c6040578e5f2192edb6c48396bf81abebb5e68c5b03e3a2f33318b8242fde34e753c74b60620ced1804d8e9588842a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
